#!/usr/bin/env bash

upsearch () {
  slashes=${PWD//[^\/]/}
  PROJECT_ROOT="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$PROJECT_ROOT/$1" && return
    PROJECT_ROOT="$PROJECT_ROOT/.."
  done
}

CUR_DIRECTORY="$PWD"
upsearch 'composer.json'

if [ ! -f "${PROJECT_ROOT}/composer.json" ]; then
  echo "composer.json file not found, please run the script from within the project."
  exit 1
fi

PATH="${PROJECT_ROOT}"/vendor/bin:"${PROJECT_ROOT}"/scripts/custom:$PATH

cd "${PROJECT_ROOT}"

git pull &&
composer install &&
cli-migrate run &&
cd web &&
drush updb -y &&
drush config-import

cd "${CUR_DIRECTORY}"

